- README.md
I've have:
- fixed some tabulation & indentation in php example
- converted the first ordered list
> Fix some coding standards in README

- README.md
The examples currently only work when Laravel is installed. This PR makes it more clear on how to use it without a framework and Laravel specific code is more concentrated to a single section.
> Moved Laravel examples in to a single section

- README.md
- src/Mpociot/BotMan/Cache/CodeIgniterCache.php
Hi mpociot,
codeIgniter cache class different...
For example use file driver below:
$this->load->driver('cache');
new CodeIgniterCache($this->cache->file); // Class is CI_Cache_file
For example use redis driver below:
$this->load->driver('cache');
new CodeIgniterCache($this->cache->redis); // Class is CI_Cache_redis
Can i remove construct limit for CodeIgniterCache?
I could use your assistance on this.. Thx
> remove codeIgniter cache construct limit

- src/Mpociot/BotMan/BotMan.php
Make an ability to use invokable controllers.
```php
$botman->hears('hello', 'App\Http\Controllers\HelloController');
```
If no `@` symbol is found in action `__invoke` method will be used.
```php
class HelloController extends Controller
{
public function __invoke(BotMan $bot)
{
$bot->reply('No, you!');
}
}
```
Implemented the same way as in Laravel.
> Add ability to use invokable controllers

- readme-slack.md
It's now possible to select that the bot should always show as online.
> Remove cons, since it's fixed by Slack

- src/Mpociot/BotMan/BotMan.php
When using the SlackRTM driver, if you use the following:
$botman->hears('Hello', function ($bot) {
$bot->reply('Hello!');
});
Then it causes an infinite loop.
The fix _seems_ pretty simply in that we check that the user isn't a bot when looping through the messages on the listen method.
> Check isBot when listening

- src/Mpociot/BotMan/Drivers/BotFrameworkDriver.php
- tests/Drivers/BotFrameworkDriverTest.php
Correctly handle Skype group chats when sending the messages to the Bot. Fixes #104 
Please note that Web Skype adds some strange character when you send a message to the bot, so the regular expression removes it. 
You can find the detailed example here: https://3v4l.org/GXvON
> Correctly handle Skype group chats

- src/Mpociot/BotMan/Drivers/FacebookDriver.php
This method compares hashed with the same time, which makes it more secure.
> Use a more secure hash comparison  method

- src/Mpociot/BotMan/BotMan.php
- tests/BotManTest.php
Named parameters {name})and regex quantifiers \d{2,4} conflict.
This PR provides:
/**
* regular expression to capture named parameters but not quantifiers
* captures {name}, but not {1}, {1,}, or {1,2}
*/
const PARAM_NAME_REGEX = '/\{((?:(?!\d+,?\d+?)\w)+?)\}/';
> support range quantifiers in regexes

- src/Mpociot/BotMan/Cache/Psr6Cache.php
- src/Mpociot/BotMan/Cache/SymfonyCache.php
- tests/Cache/Psr6CacheTest.php
The symfony cache driver is build on [PSR-6](http://www.php-fig.org/psr/psr-6/), but only works with `Symfony\Component\Cache\Adapter\AdapterInterface` implementations.
This PR applies a new PSR-6 cache drive, that works with `Psr\Cache\CacheItemPoolInterface` implementations. And the Symfony cache driver extends now the PSR-6 cache driver.
> Apply PSR-6 cache driver

- src/Mpociot/BotMan/Drivers/TelegramDriver.php
- tests/Drivers/TelegramDriverTest.php
For correct send GIF images need to use sendDocument endpoint in
Telegram driver
> Fix send GIF images in Telegram driver

- src/Mpociot/BotMan/Middleware/ApiAi.php
- tests/Middleware/ApiAiTest.php
Maximum length of sessionId parameter is 36
doc: https://docs.api.ai/docs/query
> [Api.ai] [Fix] The field 'sessionId' must not exceed 36 symbols.

- src/Mpociot/BotMan/Traits/HandlesConversations.php
You can now change the conversation cache time which is 30min by default. In order to change it just add `conv_cache_time` to the botman config.
Maybe there is a nicer way to check if the value is set in the config than my implementation. If you're ok with this PR I would add another one for the documentation.
> Make converstation cache time editable

- src/Mpociot/BotMan/Drivers/SlackRTMDriver.php
Fixes https://github.com/mpociot/botman/issues/264. Requires [version 0.2.10](https://github.com/mpociot/slack-client/releases/tag/0.2.10) of [mpociot/slack-client](https://github.com/mpociot/slack-client).
> Implement typing indicator for Slack RTM driver

- src/Mpociot/BotMan/Facebook/GenericTemplate.php
- tests/Facebook/GenericTemplateTest.php
Added the ability to define image ratio (square or horizontal) in generic templates.
Official docs: 
https://developers.facebook.com/docs/messenger-platform/send-api-reference/generic-template#payload
Example:
```
$bot->reply(GenericTemplate::create()
->addImageAspectRatio(GenericTemplate::RATIO_SQUARE)
->addElements([
Element::create('BotMan Documentation')
->subtitle('All about BotMan')
->image('http://botman.io/img/botman-body.png')
->addButton(ElementButton::create('visit')->url('http://botman.io'))
->addButton(ElementButton::create('tell me more')
->payload('tellmemore')->type('postback')),
Element::create('BotMan Laravel Starter')
->subtitle('This is the best way to start with Laravel and BotMan')
->image('http://botman.io/img/botman-body.png') …
```
> [Facebook] Image ratio

- tests/Cache/RedisCacheTest.php
- tests/Storages/RedisStorageTest.php
If the Redis extension is missing then the Redis-related tests will fail. This PR marks the tests as skipped instead
> Only run redis tests when extension loaded

- src/Mpociot/BotMan/Drivers/SlackDriver.php
- src/Mpociot/BotMan/Drivers/SlackRTMDriver.php
Allow replyInThread for Slack drivers to account for replying to an existing thread, not just starting a new thread.
Fix for #327
> Allow replying to an existing thread for Slack drivers.

- src/Mpociot/BotMan/Drivers/BotFrameworkDriver.php
- src/Mpociot/BotMan/Drivers/FacebookDriver.php
- src/Mpociot/BotMan/Drivers/HipChatDriver.php
- src/Mpociot/BotMan/Drivers/NexmoDriver.php
- src/Mpociot/BotMan/Drivers/SlackDriver.php
- src/Mpociot/BotMan/Drivers/TelegramDriver.php
- tests/Drivers/HipChatDriverTest.php
In my case (botman starter kit), these values where an empty string, so detected as 'configured'.
In the case of Hipchat, it had 1 value in the array (also empty string), so filtered that out.
> Check for empty values instead of null

- src/Mpociot/BotMan/Drivers/BotFrameworkDriver.php
- tests/Drivers/BotFrameworkDriverTest.php
Please see https://github.com/mpociot/botman/issues/344. Botframework conversations seems to be broken now.
> fix botframework not using shorthand closing tags

- src/Drivers/Facebook/FacebookDriver.php
Types method is using the wrong ID to send the API call.
> Fix typesAndWaits for Facebook

- src/Drivers/Telegram/TelegramAudioDriver.php
- src/Drivers/Telegram/TelegramFileDriver.php
- src/Drivers/Telegram/TelegramPhotoDriver.php
- src/Drivers/Telegram/TelegramVideoDriver.php
This avoid an internal server error when you try to download files that are more than 20 MB.
Now in case of an error, the download url for the attachment will be null.
> [Telegram] avoids crash when trying to download attachments larger than 20 MB

- src/Mpociot/BotMan/Storages/Drivers/RedisStorage.php
- tests/Storages/RedisStorageTest.php
This is similar to what has been discussed on #432 but targeted to the Storage system.
Note: This PR requires changes to `travis.yml` made by #438 to be merged first (not sure how to handle it in a more clean way).
> Added Authentication to RedisStorage

- src/Mpociot/BotMan/Facebook/Element.php
- tests/Facebook/ElementTest.php
Allow adding of plain array buttons on Element class for adding button type of "element_share" for Messenger Platform
> Allow adding of plain array buttons on Element class

- src/BotMan.php
- src/Messages/Matcher.php
- tests/BotManTest.php
There was a bug in the regex pattern commands and BotMan matches handling, example command:
```
$botman->hears('(I am|You are) {name}', function ($bot, $name) {
//$name should be the content of {name} but was "I am" or "You are"
});
```
Tests are provided and passed.
> Bugifix in combination of Regex and Parameters on hears commands and improved matches result

- src/Mpociot/BotMan/Drivers/SlackDriver.php
This allows to respond with rich formatted messages on Slack slash commands https://api.slack.com/slash-commands#responding_to_a_command you can do things like:
```php
$bot->reply('Hello!', [
'response_type' => 'in_channel',
]);
```
Which make's possible to reply with a message for everyone on the channel you run the command. Kind of what giphy does when you request a gif and instantly respond on "public" mode to the whole channel.
> Allow rich reply on slack slash commands

- src/Exceptions/ExceptionHandler.php
In the new ExceptionHandler added, the function `class_basename` is used, it is a Laravel function, we shouldn't use it as Botman wants to be framework agnostic.
> Do not user Laravel class_basename function in ExceptionHandler

- src/Interfaces/UserInterface.php
- src/Users/User.php
- tests/UserTest.php
This add a new property to the User interface. The goal is to be give the drivers the possibility to store the raw user data, and get it back.
You can sent object or array, but it will always return an array.
We will need to edit the drivers to use this new property.
Here are some examples:
SlackRTM:
```
return new User(
$matchingMessage->getSender(),
$user->getFirstName(),
$user->getLastName(),
$user->getUsername(),
$user->jsonSerialize() // or sympy $user, it will work too
);
```
Discord:
```
return new User(
$matchingMessage->getSender(),
$user->getFirstName(),
$user->getLastName(),
$user->getUsername(),
$user
);
```
Facebook:
```
$profileData = json_decode($profileData->getContent());
$firstName = isset($profileData->first_name) ? $profileData->first_name : null;
$lastName = …
```
> RFC User raw data method

- src/Mpociot/BotMan/Drivers/SlackDriver.php
Fixes #466.
The title attribute is mandatory for attachments, so with it images are shown correctly.
> Image attachments fix

- src/Traits/HandlesExceptions.php
- tests/Exceptions/ExceptionTest.php
- tests/Fixtures/TestClass.php
As title, accept `class@method` with exception handler, and not only closures.
> Accept exception handlers without closures

- src/BotMan.php
- src/Exceptions/Base/BotManException.php
- src/Exceptions/Base/DriverAttachmentException.php
- src/Exceptions/Base/DriverException.php
- src/Exceptions/Core/BadMethodCallException.php
- src/Exceptions/Core/UnexpectedValueException.php
- src/Handlers/ExceptionHandler.php
- tests/BotManTest.php
- tests/Exceptions/ExceptionTest.php
- tests/Storages/FileStorageTest.php
- tests/Storages/StorageTest.php
This allow to catch exceptions by their inheritance chain. 
For example:
`Exception -> BotManException-> DriverException -> DriverAttachmentException`
If a handler for DriverAttachmentException is not found, it looks for a handler for DriverException, BotManException, and finally Exception. If a handler for one of this chain is not found, the exception will be thrown.
> Inherited exceptions handlers, custom Botman internal exceptions

- src/Drivers/Tests/FakeDriver.php
This important PR is needed for the new Studio tests. It returns empty text for templates because they do not have a `getText` method. Without this the studio tests do not work.
> Return empty text for templates

- src/BotMan.php
- tests/BotManTest.php
This will keep the previous message and driver after the call of the say method.
> Fix say method to keep the previous state

- src/Drivers/Tests/FakeDriver.php
This PR adds the fake conversation message text to the value too. This makes it possible to test for the value too in the BotMan tests.
> Add conversation message to value as well

- src/Drivers/DriverManager.php
With Slack we need to verify events without a Slack token, so we need to verify it while the driver is not "configured". This PR uses the available drivers for that instead of the configured ones.
> User available drivers instead of configured ones for verify

- CHANGELOG.md
- src/BotMan.php
- src/Traits/HandlesConversations.php
- tests/BotManTest.php
This PR will cache the user received from the drivers `getUser` method. This is especially helpful for Facebook, because it will trigger an API call every time. What do you think about it @mpociot ?
> Feature - cache message user

- src/Traits/HandlesConversations.php
$this->config is an array as shown below:
```
array:3 [▼
"config" => array:1 [▶]
"nexmo" => array:4 [▶]
"web" => array:1 [▶]
]
```
We need to use `$this->config['config']['conversation_cache_time']` instead of `$this->config['conversation_cache_time']`
> Fix incorrect 'conversation_cache_time' config path in HandlesConversations.php

- composer.json
https://getcomposer.org/doc/articles/scripts.md#writing-custom-commands
> Note: Before executing scripts, Composer's bin-dir is temporarily pushed on top of the PATH environment variable so that binaries of dependencies are easily accessible. In this example no matter if the phpunit binary is actually in vendor/bin/phpunit or bin/phpunit it will be found and executed.
> Fix composer.json scripts

- composer.json
when I installed the package, noticed autodiscovery wasn't working for me.  after digging saw that it was put in `extras` when it should be in `extra`.
> fix Laravel autodiscovery

- src/Messages/Conversations/Conversation.php
- src/Traits/HandlesConversations.php
```
class TestConversation extends Conversation
{
/**
* How long should this conversation be cached (in minutes)
*/
$protected $cacheTime = 5;
/**
* @return mixed
*/
public function run()
{
...
}
}
```
This allows to set different cache time for different conversation. For example, when originating conversation developer can not be sure that user will respond immediately and thus want to set longer cache time
> Conversation cache time can be set for specific conversation to override the default value

- tests/AnswerTest.php
- tests/BotManConversationTest.php
- tests/BotManDriverEventTest.php
- tests/BotManFactoryTest.php
- tests/BotManMiddlewareTest.php
- tests/BotManTest.php
- tests/ButtonTest.php
- tests/Cache/ArrayCacheTest.php
- tests/Cache/CodeIgniterCacheTest.php
- tests/Cache/DoctrineCacheTest.php
- tests/Cache/Psr6CacheTest.php
- tests/Cache/RedisCacheTest.php
- tests/Cache/SymfonyCacheTest.php
- tests/ConversationTest.php
- tests/DriverManagerTest.php
- tests/Drivers/FakeDriverTest.php
- tests/Exceptions/ExceptionTest.php
- tests/MessageTest.php
- tests/Messages/MessageTest.php
- tests/Middleware/ApiAiTest.php
- tests/Middleware/WitTest.php
- tests/QuestionTest.php
- tests/Storages/BotManStorageTest.php
- tests/Storages/FileStorageTest.php
- tests/Storages/RedisStorageTest.php
- tests/Storages/StorageTest.php
- tests/Unit/BotManTest.php
- tests/UserTest.php
- tests/VerifiesServicesTest.php
Use [PSR-1](http://www.php-fig.org/psr/psr-1/#namespace-and-class-names) while extending PHPUnit TestCase class. This will help us when to migrate to PHPUnit 6, that [no longer support snake case namespaces](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-6.0.md#changed-1).
> Use PSR-1 for PHPUnit TestCase

- composer.json
allow 'minor' updates on this dependency. not sure if there was a reason it was initially constrained so tightly, but all test are passing with the updated version.
> update `react/socket` dependency

- src/BotMan.php
In Botman.php, line number 56 variable name is ougoingMessage. Everywhere in the Botman outgoingMessage is used so, I thought it should also be outgoingMessage.
> Change variable name ougoingMessage to outgoingMessage

- src/BotMan.php
- tests/BotManTest.php
In some case you need to have some commands with dependencies. Allow commands instances is the way to have complexe command. 
Eg: You want a command to interact with an external service like "G Suite". You want to create a directory in G Drive. You need to inject GDrive service to your command. It's not possible without this lines.
I hope this PR will be merged.
> Allow to use Command instance instead of Command class

- src/Commands/Command.php
Current docs says, that conversation should be stopped, which is misleading.
Changed to `skipped`.
> Update phpdoc for Command::skipsConversation()

- src/Messages/Conversations/Conversation.php
- tests/ConversationTest.php
This should enable something like this without serialization issues:
```php
class Example {
public function test(BotMan $bot)
{
$bot->ask($question, function (Answer $answer) {
// @var $this InlineConversation
$this->getBot()->types();
}
}
}
$bot->hears('test', Example::class.'@test')
```
I'm not really sure how to test it outside of just setting $bot and validatings it's not null.
close issue #672
> Enables usage of BotMan instance in questions outside of conversation

- src/Traits/HandlesConversations.php
Call bindTo on Conversion's Closure even it is not SerializableClosure #690
> Call bindTo on Conversion's Closure even it is not SerializableClosure #690

- src/Messages/Outgoing/Question.php
- tests/Messages/QuestionTest.php
There was an issue in (only) PHP 7.2 when calling `toWebDriver` in `Messages/Outgoing/Question`:
```
An error occurred: Warning: count(): Parameter must be an array or an object that implements Countable in /home/travis/build/Quotatis/dora/vendor/botman/botman/src/Messages/Outgoing/Question.php line 153
```
This was not detected because there was no test for this class.
This PR adds some unit tests for it and fix the issue by setting an empty array for `$actions` in the constructor.
> Fix instanciation of Messages/Outgoing/Question

- src/Drivers/DriverManager.php
- tests/DriverManagerTest.php
- tests/Fixtures/AnotherDriver.php
Hello,
So I was making a custom driver to send private HipChat notifications so I named my driver `HipChatPrivateDriver` but I noticed the name of the driver was `HipChatPrivat` and not the expected `HipChatPrivate` (missing the last **e**).
I did some digging and found an [rtrim](http://php.net/manual/en/function.rtrim.php) for getting the name of the driver (from the given name) but an rtrim looks for matching characters and not the entire string. (because `e` was in the list of characters `Driver` it returned the wrong name)
I've fixed this by replacing the function with a preg_replace where we check for `Driver` as a whole at the end of the string. (So you could have a driver called `AwesomeDriverDriver` which now turns into `AwesomeDriver` instead of `Awesom`)
I've created a new test …
> Replace rtrim with preg_replace

- src/Middleware/ApiAi.php
some of the docblock had `Wit`, so I just replaced it with `API.ai`
> replace wit with API.ai

- src/BotMan.php
I've added a handling if the getMessages() method didn't return any message in the callFallbackMessage() method.
I'm not 100% sure if just a return is good enough but it fixed it for me.
Fix for #752
> Fixed callFallbackMessage if no messages

- src/BotMan.php
- src/Drivers/HttpDriver.php
- src/Drivers/Tests/FakeDriver.php
- src/Drivers/Tests/ProxyDriver.php
- src/Interfaces/DriverInterface.php
- tests/Fixtures/TestDriver.php
- tests/Fixtures/TestDriverWithSubDriver.php
- tests/VerifiesServicesTest.php
The proposed breaking changes (changes to DriverInterface) allow the use of float seconds in the typesAndWaits() method.
> Add support for float seconds in typesAndWaits() method

- src/Messages/Matcher.php
- tests/Messages/MatcherTest.php
Slack slash command, for example `/cfp`, will be send with a trailing slash. I expanded the regex to cover a optional whitespace.
Slack will send slash commands with a trailing slash (`/cfp` will be received as `/cfp `) which causes the regex to not validate correctly.
> Accept trailing whitespace in case of using the Slack's slash commands

- src/Traits/HandlesConversations.php
$this->config is an array as shown below:
```
array:3 [▼
"config" => array:1 [▶]
"nexmo" => array:4 [▶]
"web" => array:1 [▶]
]
```
We need to use `$this->config['config']['conversation_cache_time']` instead of `$this->config['conversation_cache_time']`
> Fix incorrect conversation_cache_time config path

- src/BotMan.php
According to https://github.com/botman/botman/blob/2.0/src/BotMan.php#L535-L537 the method `say` does accept a string for the driver which is then loaded by name.
> Correct doc comment for say method

- src/BotMan.php
Added `OutgoingMessage` as an accepted type for the `$message` parameter of `BotMan::reply()`.
This fixes static analysis errors like the following from psalm.
```
ERROR: InvalidArgument - app/Path/To/SomeFile.php:13:37 - Argument 1 of BotMan\BotMan\BotMan::reply expects BotMan\BotMan\Messages\Outgoing\Question|string, BotMan\BotMan\Messages\Outgoing\OutgoingMessage provided
$botman->reply(OutgoingMessage::create(...)->withAttachment(...));
```
> Added OutgoingMessage type to BotMan::reply() $message parameter

- src/Interfaces/UserInterface.php
To prevent error messages from PHPStan like:
```
Method                                                                  
MyProject\Domain\Bot::getChatUsername()   
never returns null so it can be removed from the return typehint.
```
when using code like this:
```php
class Bot{
/** @var BotManApiClient */
private $botMan;
public function getChatUsername() : ?string
{
return $this->botMan->getUser()->getUserName();
}
}
```
> Indicate possible null values in PHPDoc @return

- src/Http/Curl.php
When used in an artisan command in L5.8 / PHP7.1.29, the curl_close command causes "* Closing connection 0" to be printed every time, for all Artisan commands. Setting verbosity to false will stop this output whilst still allowing exceptions to be caught.
> Set cURL verbosity to false to avoid console output
