src/Mpociot/SlackBot/Answer.php
Hi,
I was reading the code and thought I could add the missing doc block
=> added missing docblock

src/Mpociot/SlackBot/SlackBot.php
=> fix phpdoc that annoyed me

src/Mpociot/SlackBot/SlackBot.php
Removed some unnecessary "else" statements to keep the methods more clean and readable :)
=> Removed some unnecessary "else" statements

README.md, composer.json, src/Mpociot/BotMan/BotManFactory.php, src/Mpociot/BotMan/Cache/DoctrineCache.php, src/Mpociot/BotMan/Cache/LaravelCache.php, tests/Cache/ArrayCacheTest.php, tests/Cache/DoctrineCacheTest.php
Tests are included and I also included tests for the regular ArrayCache since it was missing.
=> Added DoctrineCache

README.md, composer.json, src/Mpociot/BotMan/Cache/SymfonyCache.php, tests/Cache/SymfonyCacheTest.php
This will probably also make some people happy :)
=> Added SymfonyCache

src/Mpociot/BotMan/Drivers/BotFrameworkDriver.php
Update OAuth scope from `https://graph.microsoft.com/.default` to `https://api.botframework.com/.default`
=> Update Microsoft Bot Framework scope to v3.1

readme-slack.md
This was a bit easier for me to parse. 
Also, I noticed that there wasn't any details for "Use a bot in combination with the Slack Event API". Should something be added at the bottom of the readme for that section?
=> Formatting for readme-slack

src/Mpociot/BotMan/Cache/CodeigniterCache.php
=> Add Codeigniter Cache

README.md
By adding a Packagist badge users can very easily see the version number of the last tagged release.
=> Make latest tagged version more visible

src/Mpociot/BotMan/Drivers/TelegramDriver.php
I guess the docblock needs some more changes but I'm not sure.
=> Remove Facebook from docblock

composer.json
=> Modify symfony/http-foundation requirement to be compatible with Laravel 5.4

src/Mpociot/BotMan/Cache/RedisCache.php
Based on phpredis, keys are prefixed for better namespacing.
=> add redis cache driver

src/Mpociot/BotMan/Middleware/ApiAi.php, tests/Middleware/ApiAiTest.php
Added the 'parameters' array on ApiAi middleware. This is very useful when working with intents.
=> Added the 'parameters' fields on ApiAi middleware

src/Mpociot/BotMan/Storages/Drivers/RedisStorage.php, tests/Cache/RedisCacheTest.php, tests/Storages/RedisStorageTest.php
This also introduces integration tests group (I suggest it's only run in travis since people won't necessarily have redis locally installed).
=> add redis storage, don't flush local redis when running tests

src/Mpociot/BotMan/Drivers/SlackRTMDriver.php, src/Mpociot/BotMan/Messages/Message.php, tests/Drivers/SlackRTMDriverTest.php
This needs mpociot/slack-client#2
=> Allow to reply with a file (Slack RTM only)

src/Mpociot/BotMan/BotMan.php, src/Mpociot/BotMan/DriverManager.php, src/Mpociot/BotMan/Drivers/FacebookAttachmentDriver.php, src/Mpociot/BotMan/Drivers/FacebookAudioDriver.php, src/Mpociot/BotMan/Drivers/FacebookImageDriver.php, src/Mpociot/BotMan/Drivers/FacebookLocationDriver.php, src/Mpociot/BotMan/Drivers/FacebookVideoDriver.php, src/Mpociot/BotMan/Message.php, src/Mpociot/BotMan/Messages/Message.php, tests/Drivers/FacebookAttachmentDriverTest.php, tests/Drivers/FacebookAudioDriverTest.php, tests/Drivers/FacebookImageDriverTest.php, tests/Drivers/FacebookLocationDriverTest.php, tests/Drivers/FacebookVideoDriverTest.php
Add FacebookAudioDriver to listen for Facebook audio files
=> Hear Facebook audio, attachment and location messages

src/Mpociot/BotMan/Drivers/FacebookDriver.php
=> Fix wrong docblock return type

.gitignore, composer.json, src/Mpociot/BotMan/Drivers/BotFrameworkDriver.php, src/Mpociot/BotMan/Drivers/Driver.php, src/Mpociot/BotMan/Drivers/FacebookDriver.php, src/Mpociot/BotMan/Drivers/HipChatDriver.php, src/Mpociot/BotMan/Drivers/NexmoDriver.php, src/Mpociot/BotMan/Drivers/SlackDriver.php, src/Mpociot/BotMan/Drivers/TelegramDriver.php, src/Mpociot/BotMan/Drivers/WeChatDriver.php
moved payload and event variables to abstract class
=> Driver variables abstraction

src/Mpociot/BotMan/Middleware/Wit.php, tests/Middleware/WitTest.php
Same issue as #266, but for Wit.ai
=> Cache Wit.ai calls

src/Mpociot/BotMan/Drivers/FacebookDriver.php, src/Mpociot/BotMan/Drivers/NexmoDriver.php, src/Mpociot/BotMan/Drivers/SlackDriver.php, src/Mpociot/BotMan/Drivers/TelegramDriver.php
=> Allow replace default values in sendRequest methods (#312)

src/Attachments/Location.php, src/Drivers/Facebook/FacebookDriver.php, src/Drivers/Telegram/TelegramDriver.php, tests/Drivers/FacebookDriverTest.php, tests/Drivers/TelegramDriverTest.php
This enable send location, file and audio for telegram, audio and file for facebook.
=> New methods for the api send

src/Facebook/ElementButton.php
add more parameters to ElementButton, those are needed for webviews
=> Messenger WebView Buttons

src/Conversation.php, src/Traits/HandlesConversations.php, tests/Fixtures/TestConversation.php
Rename given stop and skip methods to unify them
=> Unify stop and skip methods

.travis.yml, src/Mpociot/BotMan/Cache/RedisCache.php, tests/Cache/RedisCacheTest.php
=> Added Redis Authentication to RedisCache

.travis.yml, src/Cache/RedisCache.php, tests/Cache/RedisCacheTest.php
Ported changes from 1.5 (#438) to master.
=> Added Authentication to RedisCache

src/Storages/Drivers/RedisStorage.php, tests/Storages/RedisStorageTest.php
Ported changes from 1.5 (#439) to master.
=> Added Authentication to RedisStorage

src/Drivers/Tests/FakeDriver.php
Added zip with `routes/botman.php` file and `testExample.php` with all test for new features. In order to use these features branch must be used together with PR on studio-addons. 
For tests to work it is necessary to install Facebook driver.
[Archive.zip](https://github.com/botman/botman/files/1338595/Archive.zip)
=> Made changes to support new Studio test methods

src/BotMan.php, src/BotManFactory.php, src/Traits/HandlesConversations.php
http://php.net/manual/en/function.array-push.php#refsect1-function.array-push-description
> Note: If you use array_push() to add one element to the array it's better to use $array[] = because in that way there is no overhead of calling a function.
---
fix phpdoc of `__call()`,`__callStatic()`
http://php.net/manual/en/language.oop5.overloading.php#language.oop5.overloading.methods
=> change array_push() to $array[] 

src/BotMan.php, tests/BotManTest.php
```
$botman->group(['middleware' => new Middleware], function ($bot) {
$bot->group(['driver' => FacebookDriver::class], function ($bot) {
...
});
});
```
=> Group can be chained

src/Commands/Command.php, tests/BotManTest.php
```
$botman->group(['skip_conversation' => true], function ($bot) {
// all $botman->hears commands will skip conversation
});
```
```
$botman->group(['stop_conversation' => true], function ($bot) {
// all $botman->hears commands will stop conversation
});
```
=> stop_conversation and skip_conversation as group attribute

composer.json
=> Update composer.json to include version 3.4 for symfony libraries

src/Mpociot/BotMan/DriverManager.php
Use preg_replace instead of rtrim.  This handles drivers named like TwitterDriver correctly.
=> Load Driver Update

README.md
- Changed "http" to "https" everywhere I could
- Changed HipChat to Stride
- Added "www" where necessary to prevent redirects
=> Use https URLs where possible in the README

src/Drivers/DriverManager.php, src/Drivers/NullDriver.php, src/Drivers/Tests/FakeDriver.php
This PR fixes some wrong docBlock return types.
=> Fix some docBlocks

src/BotMan.php, src/BotManFactory.php, src/Middleware/ApiAi.php, src/Middleware/Wit.php
Perfomance: Using fully-qualified function calls is faster,
details and benchmarks are here:
https://github.com/Roave/FunctionFQNReplacer
=> Fix Parameter Bug in Wit and improve Perfomance

composer.json
I also use stable version of mockery/mockery
=> Syntax updates

.travis.yml
This is not considered as best practice anymore. Composer is installed with a reasonable version, so this just takes time =)
=> Updating composer is not needed

src/Drivers/Tests/FakeDriver.php, src/Drivers/Tests/ProxyDriver.php, tests/Drivers/FakeDriverTest.php
This PR adds the `getUserWithFields` method to the test drivers.
=> Add getUserWithFields method to tests

src/BotMan.php, src/Commands/ConversationManager.php, src/Messages/Attachments/Contact.php, src/Messages/Conversations/Conversation.php, src/Messages/Incoming/IncomingMessage.php, tests/BotManConversationTest.php, tests/BotManTest.php, tests/Fixtures/TestDataConversation.php
Added the ability to hear a "contact" message from Telegram
=> added telegram contact message

src/Messages/Conversations/Conversation.php
I needed the method to ask for files, so I added it
=> Add missing method

src/BotMan.php, tests/BotManTest.php, tests/Fixtures/InvokableService.php
Hello,
It's not possible with the current version to use a callable instantiated service as a callback. This PR solves this.
=> Allow any callable as a callback

.travis.yml
Add tests for PHP 7.4.
---
Closes https://github.com/botman/botman/pull/1070
=> Add tests for PHP 7.4.

src/Messages/Outgoing/Actions/Select.php
=> Add Select action for Slack

src/BotMan.php, tests/BotManDriverEventTest.php, tests/BotManTest.php
It's a simple PR, totally understable if it's closed. I thought it will follow the same syntax as the event listening #849
=>  Allow BotMan to hear from an array of commands

src/Http/Curl.php
=> Fix type of Curl::prepareRequest()
